name: Download and Build

on:
  schedule:
    - cron:  '0 0 12 * *'
  workflow_dispatch:
jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U requests beautifulsoup4
          
      - name: Download files
        run: |
          python pyrucsql.py
          
      - name: Create database
        run: |
           psql "create database ruc;"
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432

      - name: Import data
        run: |
           psql ruc < ruc.sql
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432

      - name: Export data
        run: |
           pg_dump  --no-password  --format custom --blobs --verbose --file "tmp/postgres.backup" "ruc"
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
  
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Blas Fernández
          author_email: blasferna@gmail.com
          message: 'update ruc.zip'
          add: '.'
