name: Download and Build

on:
  schedule:
    - cron:  '0 0 1 * *'
    - cron:  '0 0 10 * *'
    - cron:  '0 0 25 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install UnRar
        run: sudo apt-get install unrar

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U requests==2.25.1 beautifulsoup4==4.10.0 pandas==1.3.5 openpyxl==3.0.9
          python -m pip install -U tabula==1.0.5
          
      - name: Download files
        run: |
          cd data && python download.py

      - name: Upload ruc
        run: |
          cd data && curl -T ruc.db ${{ secrets.RUC_DB_URL }} -u "${{secrets.RUC_USER}}:${{secrets.RUC_PASSWORD}}"


      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'update ruc.zip'
          add: '.'
